### ISSUE TITLE
FileChooserDialog : unable to use with a parent fragment

### ISSUE THREAD

**Issue by thibautd** [afollestad/material-dialogs#1152]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of Material Dialogs.
- [X] I have given my issue a non-generic title.
- [X] I have read over the documentation (before asking questions on how to do something).

I'm using `MaterialDialog` inside a retained DialogFragment, and I would like to open a second dialog on a button press (A `FileChooseDialog`). But the callback of this dialog is mandatory an activity, because it's obtained in `onAttach()` using `getActivity()`.

A possible solution which would allow the dialog to be used as as a child fragment would be to do the following in onCreate() :

```java
if (getParentFragment() != null)
    mCallback = (FileCallback) getParentFragment();
else
    mCallback = (FileCallback) getActivity();
```

Do you think this could be a possible modification ?

**Comment by afollestad** [comment]
This library enforces the use of an `Activity` because the `DialogFragment` attaches to the `Activity` and calls `onAttach(Activity)`. This happens after rotation too, so the callback reference can be restored. There is no way to do this from another `Fragment`. 

You should attach the File Chooser to your parent `Activity`.

**Comment by thibautd** [comment]
This is not always true. If the parent fragment is a retained fragment (which is my case), the instance of the parent fragment does not change on screen rotation.
