### ISSUE TITLE
itemsCallbackSingleChoice in MaterialDialog not scrolling correctly to preselected index

### ISSUE THREAD

**Issue by jmartingit** [afollestad/material-dialogs#1173]
Hi Aidan,

I've made a jump from Material Dialogs 0,8.5.5 to 0.9.0.1 and I've noticed that now the single choice dialogs don't scroll correctly to the preselected index.

Here are other things that I've updated in my app:
- Target skd from 23 to 24
- Support libraries from 23.4.0 to 24.2.0

The issue happens in all versions from Android 4.0 to 7.0.
###### More info:
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).
###### Include the following:
- Material Dialogs version: 0.9.0.1
- Device OS version: all versions from 4.0 to 7.0
- Device Name: Nexus 5, Nexus 5x and several older Samsung and Sony devices
###### Expected Result

The dialog shoud scroll so that the preselected index falls in the middle.
###### Actual Result

The dialog scrolls but the preselected index falls out of view (the dialog stops several places before the preselected index).

**Comment by danielesegato** [comment]
I can confirm this.

I've also digged a little in the code which basically works like this:

1. see how many items are currently shown
2. remove from the selected item position half the count of that number
3. scroll to the computed value

This assume that:

- the recyclerview would scroll to the point that the indicated position is the first visible one
- items have all the same height

The first assumption is completely wrong, the list actually scroll down until the indicated position is visible and stop. So if anything it would be more correct to add positions instead of subtracting it (and check it does not go over the max value).

Even "fixing" it like that it may not necessary be a fix. In fact how the actual scroll happens depends on the LayoutManager implementation and the library shouldn't try to guess it. It should just ask for it to scroll to the given position and nothing else and, eventually, provide a custom callback for that to be handled by the user.

For example the `LinearLayoutManager` has an handy `scrollToPositionWithOffset` that, if you know the height of the view and the average height of each item, let you position your view exactly in the middle.

**Comment by danielesegato** [comment]
By the way this is a blocking bug for me: not using your library for this specific reason.
