### ISSUE TITLE
Support for all layout manager types

### ISSUE THREAD

**Issue by raviteja83** [afollestad/material-dialogs#1186]
###### Include the following:
- Material Dialogs version: `0.9.0.0`
- Device OS version: `4.4.4`
- Device Manufacturer: `Xiaomi`
- Device Name: `Redmi 1s`

Please add support to StaggeredGridLayoutManager in the recyclerview.It currently supports only LinearLayoutManager and GridLayoutManager.

**Comment by danielesegato** [comment]
I would actually support ANY layout manager, I don't see why not :)

**Comment by afollestad** [comment]
@danielesegato because not all the required methods are abstract methods. Each `LayoutManager` implementation has their own methods for retrieving data used by this library in most cases.

**Comment by danielesegato** [comment]
@afollestad you use them in 2 point:

Here: to try to center the currently selected item in the screen:
https://github.com/afollestad/material-dialogs/blob/990450904ee440efc587a269c9867bcd8e4a79fe/core/src/main/java/com/afollestad/materialdialogs/MaterialDialog.java#L136

Which is wrong and shouldn't be done like that, see my comment on this other bug: #1173

And here to check if the recyclerview can scroll: https://github.com/afollestad/material-dialogs/blob/e79d3c0117eb4a50cdda8b274bffe50897c0040b/core/src/main/java/com/afollestad/materialdialogs/internal/MDRootLayout.java#L527

which is also a bad idea, and you should be using `RecyclerView.canScrollVertically()` method to check that.

So you really have no reason to limit on those 2 layout.
Even if you want to add support specific for those two you can have a fallback or check if the other LayoutManager implement an interface you specify or just require the user to specify that interface implementation on the builder.

**Comment by afollestad** [comment]
Feel free to make a PR, then.

**Comment by afollestad** [comment]
@danielesegato you're pretty condescending, aren't you? :P

**Comment by danielesegato** [comment]
> @danielesegato you're pretty condescending, aren't you

no I'm not :) [dunno why you removed the comment]
I just wanted to give you suggestions to improve your library.

I'm not using your library right now, I tested it out and I always look at the code when I do. Since I'm not using it I can't spend the time on doing PR on it.

You can chose to ignore what I said but it doesn't make it false.

I like to go straight to the point, I'm not good at being polite and do not even make an effort to be most of the time. If I took the time to open these two bugs and write all that. It is because I think you did a good job with your library and that it  with this 2 little improvement it could get so much better.

By the way I saw you did the modifications I suggested, happy about that :) I'm gonna have a look at it again next project ;-) good job there
