### ISSUE TITLE
Html.fromHtml() broke content formatting when not using CDATA

### ISSUE THREAD

**Issue by FrancescoCapari** [afollestad/material-dialogs#1278]
Similarly how #1222 broke the "\n" in a resource string, no html tags are working in the content when passed as resource ids and CDATA is not part of the resources (which it doesn't have to).

So long story short - the change where you replaced the CharSequence (getText()) for Html.fromHtml() broke HTML formatting.

**Comment by yukuku** [comment]
When passing a formatted text from string resource, getText() should be called instead of getString() plus Html.fromHtml(). 

Using getString() will strip off all formatting attributes from a string resource, so passing that to Html.fromHtml() won't have any effect.

Please do not use Html.fromHtml() automatically. Sometimes the dialog text contains user-entered text. Some user-entered text may contain `<` , and this will be interpreted as a tag opening and the rest of the message will be gone.

**Comment by yukuku** [comment]
There should be a separate method if the user wants to interpret HTML tags in the string resource file. For example, add `.contentHtml(@StringRes int resId)` and  `.contentHtml(@StringRes int resId, Object ... args)` that uses Html.fromHtml().

`.content(@StringRes int resId)` should always use getText() internally, consistent with how all `setText()` and similar methods in Android SDK works.

**Comment by FrancescoCapari** [comment]
I absolutely agree with what @yukuku said. `.content(@StringRes int resId) ` should always internally use getText(). Creating several instances of String (String.format and String.replace), converting them to Spannable by passing it into the Html.fromHtml() is just an absolutely unnecessary (although small) performance drawback, when one only wants to get an CharSequence implementation with replaced params.

The Html.fromHtml() should never be called automatically - also for the reason that it does not work if you don't put CDATA into your resources.

**Comment by yukuku** [comment]
As an additional note, MaterialDialog's `.title(@StringRes int titleRes)`, `.positiveText(@StringRes int positiveRes)` and its siblings, also use `getText()`. It makes me feel that `.content(@StringRes int resId)` should also use `getText()` to make it work uniformly.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.9.3.0
