### ISSUE TITLE
Separate ColorChooserDialog's Callback & Activity paramaters

### ISSUE THREAD

**Issue by AdityaAnand1** [afollestad/material-dialogs#1368]
I'm wondering whether it would be possible to separate out the `CallBack `and `Activity `that the `ColorChooserDialog.Builder()` method needs. 

I'm not sure how common my use case is, but I'd like to use `ColorChooserDialog` inside my own custom view and having to hook in the colorSelection callback through the activity makes for some very messy code.

**Comment by afollestad** [comment]
`ColorChooserDialog` is a `DialogFragment` so an `Activity` is necessary to attach to a `FragmentManager`.

**Comment by AdityaAnand1** [comment]
Yeah sure but I mean:

`ColorChooserDialog.Builder(Activity activity, ColorChooserDialog.Callback callback)`

I'm saying having the activity itself implement the callback is a bit inconvenient. Simply providing, say an anonymous class as a second parameter would allow us to decouple the callback from the activity.

**Comment by AllanWang** [comment]
I'm facing a similar issue with this. To use a ColorChooserDialog, our activity now must implement the callback.

What if the dialog checks if the context is an instance of the callback before calling it so we can simply pass an activity? Or the color chooser dialog can have setColorCallback as suggested above.

**Comment by afollestad** [comment]
A Context and callback cannot be serialized or parceled. Even if they could, they would not be valid with a screen rotation since the Activity recreates and the reference would no longer be valid.

**Comment by afollestad** [comment]
The current Activity on the other hand gets reattached to the `DialogFragment` every time.

**Comment by AdityaAnand1** [comment]
Indeed, I see the problem. We're casting `callback = (ColorCallback) activity;` and it wouldn't be possible to pass in a custom parameter since that's not how DialogFragments work so there's nowhere else for the ColorCallback to be implemented.

:/

Still, I wish there was since right now I have to pass the ColorCallback calls from the activity to some place where they can be handled and that leaves a gaping hole in that place (in terms of modularity) as it's rather awkward to either expose the implementation in that place to the activity or have to pass around the callbacks.

If anyone can think of any workarounds at all, please feel free to share.

**Comment by AllanWang** [comment]
@AdityaAnand1 im going to make a version where is closes on rotation like all the other dialogs without fragments. Hopefully with this I can also make a color picker for shared preferences, since a callback is just settings the value in the prefs

**Comment by AllanWang** [comment]
I ended up [rewriting](https://github.com/AllanWang/KAU/blob/master/library/src/main/kotlin/ca/allanwang/kau/dialogs/color/ColorPickerDialog.kt) the dialog so that it fits my needs. It's redone in Kotlin, and I plan on adding stuff like animating the selection and switching to a recyclerview so the same adapter is used with different color items.

In regards to the callback, what if this dialog is initialized by a fragment or view whose activity implements the callback? In that case, the context given is but a context and cannot be used in the builder, but it still holds the callback. From what I'm aware of, intersection casting is still not possible with Java, and it seems to not be available for [kotlin](https://stackoverflow.com/questions/44448651/is-intersection-casting-possible-in-kotlin/44453604#44453604) either.

The workaround is to have the fragment/view call on the activity to then create the dialog, but that seems a bit long winded.
