### ISSUE TITLE
Custom view dialogs should show dividers if there's any scroll view children automatically

### ISSUE THREAD

**Issue by afollestad** [afollestad/material-dialogs#156]

**Comment by teslacoil** [comment]
Unless I'm misreading, this was part of my earlier change for removing the scrollview wrapper (and is still working after your refactoring). `invalidateCustomViewAssociations` searches for views touching the top and/or bottom (`canViewOrChildScroll`) and enables the appropriate divider. It checks top/bottom separately, and only if exactly touching so that if you have other fixed views or padding (and your own frame/divider/whatever) the divider isn't enabled.

This is why I left the TODO for RecyclerView ( #158 ). I personally am not using any RecyclerViews in custom dialogs and it'd require a dependency on the recyclerview support lib, so it didn't seem worth it unless there is actual demand.

**Comment by afollestad** [comment]
Oddly enough I don't remember actually created this issue o.O

**Comment by afollestad** [comment]
I think I intended it to be this, and was too tired to notice I explained the wrong thing (it's 1:57 am here):

https://github.com/afollestad/material-dialogs/issues/157

**Comment by afollestad** [comment]
and/or this: https://github.com/afollestad/material-dialogs/issues/158
