### ISSUE TITLE
Change font size

### ISSUE THREAD

**Issue by severinewillez** [afollestad/material-dialogs#1724]
How can I change content, button text and title font size without using custom view ?
Is it possible ? Thanks in advance.

**Comment by afollestad** [comment]
Currently, no, it's not possible

**Comment by hadi72h** [comment]
@severinewillez 
@afollestad 

it's possible, override these dimens

`
<dimen name="md_title_textsize" tools:override="true">@dimen/large_text_size</dimen>
<dimen name="md_message_textsize" tools:override="true">@dimen/default_text_size</dimen>
 <dimen name="md_action_button_textsize" tools:override="true">@dimen/default_text_size</dimen>
`

**Comment by afollestad** [comment]
Oh duh, I forgot my own feature

**Comment by afollestad** [comment]
Actually no, those attributes do not exist in 2.0.

**Comment by hadi72h** [comment]
I'm using 2.0.0 and it works.
If it works, Don't touch it 😉

**Comment by afollestad** [comment]
Weird 😮 the available attributes are in https://github.com/afollestad/material-dialogs/blob/master/core/src/main/res-public/values/public.xml

(And in the Theming section of the README)

**Comment by hadi72h** [comment]
Android studio without this (tools:override="true") just show bellow warning message but it works.

Overriding @dimen/md_title_textsize which is marked as private in com.afollestad.material-dialogs:input. If deliberate, use tools:override="true", otherwise pick a different name. less... (Ctrl+F1) 
Inspection info:Private resources should not be referenced; the may not be present everywhere, and even where they are they may disappear without notice.  To fix this, copy the resource into your own project instead.  Issue id: PrivateResource

**Comment by afollestad** [comment]
Don't plan to implement this as a feature because the current text sizes are what they are for a reason.

Messing with them causes lots of layout problems as well, especially in the action buttons.
