### ISSUE TITLE
Extra white space at the top AND wide display of date/time dialogs

### ISSUE THREAD

**Issue by jeffdcamp** [afollestad/material-dialogs#1757]
The Material Dialog date/time dialog has some unneeded white space at the top of the dialog.... and the dialog seems to be too wide

MaterialDialog Code:

```
        MaterialDialog(requireContext()).show {
            datePicker(currentDate = date.toCalendar()) { _, newDate ->
                viewModel.birthDate.set(newDate.toLocalDate())
            }
        }
```
Result (extra around the edges):

![date-materialdialog](https://user-images.githubusercontent.com/1479095/54707617-22127500-4b07-11e9-8d65-37e99854648b.png)

VS

Code:

```
        val birthDatePickerDialog = DatePickerDialog(requireActivity(), DatePickerDialog.OnDateSetListener { _, year, monthOfYear, dayOfMonth ->
            viewModel.birthDate.set(LocalDate.of(year, monthOfYear + 1, dayOfMonth)) 
        }, date.year, date.monthValue - 1, date.dayOfMonth)
        birthDatePickerDialog.show()
```

Result:

![date-android](https://user-images.githubusercontent.com/1479095/54707771-74ec2c80-4b07-11e9-8919-255d085fe7cb.png)

**Comment by afollestad** [comment]
<img src="https://user-images.githubusercontent.com/1820165/54712543-c72e4d00-4b09-11e9-8a35-50b49b8fc32c.png" width="300" />

**Comment by goyalish** [comment]
I have faced a similar issue. In my case, I was passing the dialog context instead of the activity's context.

Where are you showing the DatePickerDialog from? Check what context is getting passed.

For a quick fix try passing the activity for the DatePickerDialog(activity,...) So that it always gets the activity context.

Java DatePickerDialog(getActivity(),...)

Kotlin DatePickerDialog(activity,...)
