### ISSUE TITLE
Failed to resolve: com.afollestad:material-dialogs

### ISSUE THREAD

**Issue by hateum** [afollestad/material-dialogs#295]
I can't add this library to gradle:
Error:(41, 13) Failed to resolve: com.afollestad:material-dialogs:0.6.3.4

**Comment by naXa777** [comment]
I can't add this library too.

**Comment by dahvlh** [comment]
me 2

Error:(23, 13) Failed to resolve: com.afollestad:material-dialogs:0.6.7.0

**Comment by naXa777** [comment]
use another repository:

    repositories {
        jcenter()
    }

**Comment by Gusher** [comment]
Having this same issue...

Error:(43, 13) Failed to resolve: com.afollestad:material-dialogs:0.6.0
<a href="openFile">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

I do have listed...

repositories {
    jcenter()
}

**Comment by afollestad** [comment]
@Gusher that version is no longer published. The reason is discussed in another issue.

**Comment by Gusher** [comment]
How do I go about solving this? Am using Android Studio...

**Comment by afollestad** [comment]
0.6.0 was very, very old. The current version is listed in the README file.

**Comment by hesy007** [comment]
Error:(34, 13) Failed to resolve: com.afollestad.material-dialogs:core:0.8.1.0

**Comment by Servus7** [comment]
Same here.
Error:Failed to resolve: com.afollestad.material-dialogs:core:0.8.1.0

**Comment by congnt24** [comment]
same for me
Error:Failed to resolve: com.afollestad.material-dialogs:core:0.8.1.0

**Comment by congnt24** [comment]
I add it to build.gradle and it work
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

**Comment by afollestad** [comment]
The Gradle blocks in the README are supposed to go in the build.gradle file of your app module, not the entire project, like it says. 

Although the repository one will still work there.

**Comment by bgenchel** [comment]
"Could not find com.afollestad:material-dialogs:0.8.5.1"

from the line: 
compile 'com.afollestad:material-dialogs:0.8.5.1' in build.gradle.

I followed all the other steps in the readme.

**Comment by YongHuiLuo** [comment]
Why can't find in your latest version in jcenter?

**Comment by cooervo** [comment]
this worked for me:

http://stackoverflow.com/a/32900570/4031815

**Comment by Servus7** [comment]
@YongHuiLuo @bgenchel  you need to add this dependencies to your **projects build.gradle** file:
```
buildscript {
    repositories {
        jcenter()
    }
}

allprojects {
    repositories {
        jcenter()
    }
}
```

**Comment by bgenchel** [comment]
@Servus7 I have both those things in my project already :(

**Comment by plusCubed** [comment]
@Servus7 @YongHuiLuo @bgenchel The current material-dialog versions are hosted on jitpack and have core/commons modules. Please follow the README.

**Comment by bgenchel** [comment]
I *DID* follow the readme, and it got me no where. That is why we are having this discussion. 

@cooervo That actually worked to get me past the first error, but now I'm getting this:

> Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'. 

Does this error come from this repo also?

**Comment by plusCubed** [comment]
@bgenchel The readme is up-to-date and has the latest repo information. You missed several things which lead to the error: the omission of :core and using jcenter instead of jitpack, which are both specified in the readme and would've worked fine if you just copied it. Nevertheless, I see you've figured it out. 

That error is almost certainly from your specific configuration - the sample project runs fine, so please take a look at that. I'm guessing something to do with your target or compile API, since that is a lollipop+ style.

**Comment by bgenchel** [comment]
@plusCubed I can assure you that the first thing that I did when I ran into this issue was go to the readme and follow it exactly. I tried with core, and have had jitpack included the whole time. Since you haven't seen my project, it appears to me that your statements are a bit presumptuous. 

Either way, I'm actually trying to get a project working that I inherited from some other developers, and so am not really able to easily see what configuration problems could cause this error to arise. Do you have any ideas?

**Comment by plusCubed** [comment]
@bgenchel I was commenting on your comment earlier of this error: `compile 'com.afollestad:material-dialogs:0.8.5.1' in build.gradle.` The stackoverflow link is also just basically an older configuration of what is in the readme right now.

Like I said, that is most probably due to some things with API levels since that is a lollipop+ resource. The library doesn't use that resource, and supports back to API 8, so it's something else in your project.

**Comment by coderkiran** [comment]
Error:(29, 13) Failed to resolve: com.github.afollestad.material-dialogs:core:0.8.5.1 Show in File
Show in Project Structure dialog

**Comment by tomiu** [comment]
+1

**Comment by wujiyu115** [comment]
+1

**Comment by tomiu** [comment]
Upgrading to Gradle 2.11 solved the issue for me.
https://github.com/tomiu/material-camera/commit/f8eb18bc6a6c5e9b4e1d09075e1478c0bb246d95

**Comment by mrzulkarnine** [comment]
In my situation, I'm using version 0.8.5.3 to make the sync success!

compile('com.github.afollestad.material-dialogs:core:0.8.5.3@aar') {
        transitive = true
    }

**Comment by yutingzhidong** [comment]
I do like the following in my build.gradle and it worked .

repositories {
    maven { url "https://jitpack.io" }
}


//    material-dialogs
    compile('com.afollestad.material-dialogs:core:0.8.2.0@aar') {
        transitive = true
    }
    compile('com.afollestad.material-dialogs:commons:0.8.2.0@aar') {
        transitive = true
    }

**Comment by afollestad** [comment]
@yutingzhidong I wouldn't recommend using such an old version.

**Comment by a564068328** [comment]
repositories {
    maven { url "https://jitpack.io" }
}
The perfect solved my problem!
