### ISSUE TITLE
Single choice list autoscroll

### ISSUE THREAD

**Issue by msutherland4807** [afollestad/material-dialogs#372]
Is there a way that the single choice item list can auto-scroll to the initially selected item (in a large list where selected is part-way down)?

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.6.6.2

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/v0.6.6.2

**Comment by msutherland4807** [comment]
Is there a way to get this added to lists with an adapter? Or should it just be done manually (with an `OnShowListener` or something)? I have a custom adapter with a RadioButton as in the screenshot

Thanks again
![screenshot_2015-03-28-11-03-28 1](https://cloud.githubusercontent.com/assets/5905483/6882208/40f672f6-d53a-11e4-976e-b1ff9363dc98.png)

**Comment by afollestad** [comment]
There's no way for it to automatically know you're list is a single choice
list when you're using a custom adapter so it'd have to be done manually.

It actually happens before on show since there's a delay before the on show
listener is called.

See the `checkIfListInitScroll()` method in MaterialDialog.java.

**Comment by sreichholf** [comment]
checkListInitScroll is currentyl causing an ArrayOutOfBoundsException when no item is selected in a MultiChoice List.

**Comment by afollestad** [comment]
@sreichholf https://github.com/afollestad/material-dialogs/releases/tag/v0.6.6.3
