### ISSUE TITLE
Hide top/bottom divider when scrolled to top/bottom

### ISSUE THREAD

**Issue by plusCubed** [afollestad/material-dialogs#397]
Like design guidelines and 5.1 dialogs (though they didn't add enough padding so it looks weird).

**Comment by afollestad** [comment]
Are you talking about the Gradle version or current repo code? This was all completely redone by Kevin Barry.

**Comment by plusCubed** [comment]
Gradle version. Has this enhancement already been implemented in repo code?

**Comment by afollestad** [comment]
Yeah, although there's still some issues left to fix.

The related PRs are https://github.com/afollestad/material-dialogs/pull/392 and https://github.com/afollestad/material-dialogs/pull/396

The first pull request has a list of problems I found, however everything is signifantly faster since Kevin implemented a custom root layout and class for the action buttons. There's an open issue for the required fixes also.

**Comment by plusCubed** [comment]
Huh, I just compiled the latest repo code and it doesn't seem to be there? 
Clarification: in the long list/any other container that scrolls, when it is scrolled completely to the top, the top divider should be invisible. Likewise, when scrolled to the bottom, the bottom divider should be invisible. In all other cases, such as when I am in the middle of the list, both dividers should be visible. This doesn't seem to be implemented.

**Comment by plusCubed** [comment]
Working on adding this right now.

**Comment by afollestad** [comment]
Ohh sorry I misread what you meant since I read it kinda fast. Sounds good

**Comment by teslacoil** [comment]
I considered doing this as part of the padding change, but it's a bit more complicated for custom views so I figured I'd leave it for another changeset. For the builtin list you can set an onScrollListener, but for custom views that wouldn't really work unless we had the client set it's own listener. However another approach could be that MDRootLayout does the checks in onDraw, though it might need some logic to invalidate the area of the dividers when the content is invalidated (for the scroll).

**Comment by plusCubed** [comment]
@teslacoil Actually, I am implementing the onScrollChangeListener in ViewTreeObserver - it seems to work universally for all views.

**Comment by afollestad** [comment]
This is working great, I don't think the RecyclerView note will be too much of an issue right now

**Comment by teslacoil** [comment]
This incorrectly shows dividers for custom views that have fixed content in one position and a scrollable view in the other. For example a fixed preview image at the top and a listview underneath, when scrolled the divider will be drawn under the title bar even though content never scrolls under the tile. This could be fixed by confirming the scrollable views position in invalidateDividersVisibility or using a separate scroll listener for top/bottom views.

**Comment by plusCubed** [comment]
@teslacoil Ah, good catch, I'll fix it. I think I'll use separate scroll listeners.

**Comment by afollestad** [comment]
Once that's done, I think we should be just about ready for a release, a very large one at that.

I pushed two small fixes just now, also.

**Comment by teslacoil** [comment]
Oh and the divider isn't hidden if the dialog no longer needs to scroll (see the FolderChooser sample). Probably just needs to unset DrawDividers in onMeasure

**Comment by plusCubed** [comment]
@teslacoil Noted, I'll fix that.
