### ISSUE TITLE
Change margins added in 0.7.0.0 release manually

### ISSUE THREAD

**Issue by MrBrightside29** [afollestad/material-dialogs#408]
Hi,
I created a MaterialDialog with a custom view that contains a LinearLayout with a FrameLayout for the title and a custom ListView. Since last release and the new introduced margins, my custom dialog looks bad because the title has a colored background as you can see in the attached screenshot.
Is there a way to change the top margin to avoid the white frame?

Thank you!

![screenshot_2015-04-07-13-14-22](https://cloud.githubusercontent.com/assets/6217462/7022126/df5b6d0c-dd28-11e4-80b8-3e9fd15c5a89.png)

**Comment by afollestad** [comment]
Try putting `android_marginTop='-24dp'` on the pink view, maybe a bit less

**Comment by afollestad** [comment]
Oops typo

**Comment by MrBrightside29** [comment]
Tried but it doesn't work. I've tried putting it into the container layout of the custom view and into the FrameLayout that has the pink background and the white frame is still there.

**Comment by afollestad** [comment]
Hmm, I'm in class but @teslacoil or @plusCubed could possibly help in the meantime

**Comment by teslacoil** [comment]
Some workaround options:
1) Make the button part of your customview (which is not wrapped in a scrollview), then the dialog won't add any margins.
2) Use the real title instead of including it as part of your custom view and do dialog.findViewById(R.id.titleFrame).setBackgroundColor after building the dialog.
3) Copy the md_stub_titleframe.xml from the material-dialogs source into your project, and add the background color there. This would apply to all material-dialogs in your app though and you would need to copy again after updates to material-dialogs that change the title frame.

(1) Risks future padding changes and means you have to handle the button yourself, (2) risks future layout changes or the resource name changing. Personally I think (2) is best.

If there's lots of demand for adjusting the default margins we could add them as options to the builder, but I'd be inclined not to as it adds complexity both to the API and to the measure/layout code. Making something like (2) into a official api (setTitleBackgroundColor) might be reasonable alternative.

**Comment by MrBrightside29** [comment]
Ok, thanks for the reply! I will try the second workaround and let you know.

**Comment by MrBrightside29** [comment]
I don't know why but I'm getting a NullPointerException when try to set the background color. Here is my code:
```
MaterialDialog dialog = new MaterialDialog.Builder(MyPlansActivity.this)
                            .title(plan.settings_plan_name)
                            .titleColor(R.color.white)
                            .customView(R.layout.dialog_header, false)
                            .positiveText(R.string.add_more_people)
                            .callback(new MaterialDialog.ButtonCallback() {
                                @Override
                                public void onPositive(MaterialDialog dialog) {
                                    addMorePeople(plan.planId, plan.guests);
                                }
                            })
                            .build();
                    LinearLayout titleFrame = (LinearLayout) dialog.findViewById(R.id.titleFrame);
                    titleFrame.setBackgroundColor(getResources().getColor(R.color.md_pink_500));                    
                    ListView dialoglistView = (ListView) dialog.getCustomView().findViewById(R.id.membersListView);
                    PlanMembersAdapter dialogAdapter = new PlanMembersAdapter(MyPlansActivity.this, membersNamesArray, membersAttendanceArray, myName);
                    dialoglistView.setAdapter(dialogAdapter);
                    dialog.show();
```

**Comment by afollestad** [comment]
@MrBrightside29 I cleaned up your code a little bit to use Java syntax highlighting and correct the indentation.

I'd have to look into that crash a little bit more, but just so you know: rather than using a custom view, you could just use a custom adapter (`MaterialDialog.Builder#adapter()`), unless there's something special in your custom view that's not a ListView.

**Comment by afollestad** [comment]
If I were you, I'd try using `dialog.getView().findViewById(int)` rather than `dialog.findViewById()`. `getView()` returns a direct reference to the view inflated by this library.

**Comment by MrBrightside29** [comment]
It works now using dialog.getView().findViewById(int)! Thank you very much for your help!

**Comment by afollestad** [comment]
Great! You're welcome!
