### ISSUE TITLE
Can both itemsCallbackSingleChoice() and callback() be enabled?

### ISSUE THREAD

**Issue by jiechu** [afollestad/material-dialogs#431]
Now I have a request to implement a single choice list with two buttons. It is not necessary to implement it by custom view. But when I try to use both itemsCallbackSingleChoice() and callback(), the first callback is callback -> onPositive not itemsCallbackSingleChoice -> onSelection. I would expect since I have chosen an item, the dialog should firstly handle the onSelection, when I click the positive button, then the dialog handle the button.

**Comment by afollestad** [comment]
Well, actually how it works when `alwaysCallSingleChoiceCallback()` is disabled, is the positive callback gets sent first and then selection gets called afterwards. This is logical because pressing the positive action button is what triggers the single choice choice callback to be sent.

The code for this logic starts here: https://github.com/afollestad/material-dialogs/blob/master/library/src/main/java/com/afollestad/materialdialogs/MaterialDialog.java#L294

If you enable `alwaysCallSingleChoiceCallback()`, the callback will be sent everytime the user changes selection.
