### ISSUE TITLE
Why do you keep removing binaries from JCenter?

### ISSUE THREAD

**Issue by harri35** [afollestad/material-dialogs#567]
Why do you keep removing binaries from JCenter? 
The "com.afollestad:material-dialogs:0.7.2.8" is not available anymore. And I can't just trivially update - your constant updates keep breaking my app. If I just update from 0.7.2.8 to 0.7.5.5 then EditText cursors are now white in the whole app. I have to use compile 'com.afollestad:material-dialogs:0.7.5.5', { transitive = false } to overcome this. But will this break something in your lib? Are you using a different version of AppCompat than me?
Please just keep the binaries up like all the other lib owners do.

**Comment by afollestad** [comment]
Because I do not have unlimited storage on Bintray.

Not sure what you mean by "keep". The entire project was removed by accident before.

**Comment by harri35** [comment]
First time it was when the whole lib was removed and now this is the second time I have had to figure out the upgrade. You do understand how this breaks the whole point of JCenter repo if I can't trust the binary being there?
If you have unlimited space then maybe divide the binaries into releases and snapshots? And keep the releases as long as possible?

**Comment by harri35** [comment]
Hmm, looking at https://bintray.com/account/pricing?tab=account&type=pricing This says that OSS artifacts are completely free? So how is the storage limited then?

**Comment by mendhak** [comment]
If you are reaching a limit, it would be worth contacting them to get your storage limit extended: https://twitter.com/bintray/status/479648482530041857

You can also go through Sonatype and have your libraries published on Maven Central.  It's a lot of waiting but once you do it, it isn't too difficult from there onwards. 

Having said that, the size of your files is trivial and you shouldn't be reaching these limits, I've got several large files up there and haven't hit any limit.  

Please understand that it is not trivial to keep updating a project's dependencies; it's not always a drop-in-replacement and quite often a juggling act of dependencies, which is why the trust factor is quite important.
