### ISSUE TITLE
How to set minLength on a input dialog?

### ISSUE THREAD

**Issue by shifarshifz** [afollestad/material-dialogs#574]
Is it possible to set minLength on input (EditText) dialog like inputMaxLength?

**Comment by afollestad** [comment]
Currently there's no support for that.

You can manually invalidate your input dialog by calling `alwaysCallInputCallback()` in the `Builder` so that the input callback is invoked everytime the user adds or deletes a character. You can enable or disable the EditText from code based on whether or not the input is long enough.

**Comment by afollestad** [comment]
I've added a custom input dialog invalidation example to the sample project.

**Comment by shifarshifz** [comment]
Thanks for the response Aidan. by the way, I've read abt you from you portfolio aidanfollestad.com . nice one. and I would like to keep in contact with you. Is it possible to contact you through Hangouts/Gmail ?
