### ISSUE TITLE
The ability to hide the progress indicator at a later point in time

### ISSUE THREAD

**Issue by danielfaust** [afollestad/material-dialogs#587]
I'm implementing a dialog which shows a progress animation together with the text "Synchronizing...". When sync is done, I change the content text to whatever the result is and close it two seconds later, but I'm unable to remove the progress indicator when changing the text.

On an indeterminate progress dialog this is the progress animation, on other progress dialogs the indicator in general. This is specially irritating on indeterminate progress dialogs, since the ongoing animation will suggest that there is still something going on in the background.

It would be useful to have something like a hideProgressIndicator() method.

Currently I'm cancelling the progress dialog and creating a new one, but this doesn't look smooth.

----

This is troublesome. I attempted to play with the following:

```java
View vProgress = dlgAction.getView().findViewById(android.R.id.progress);
vProgress.setAlpha(0.0f);
```

and also some animation stuff, but the results are somewhat more distracting than having the dialog disappear and reappear again.

I don't think that there is a quick fix to it, so this feature request should possibly recieve a really low priority. That's at least what I'd recommend.

**Comment by boggogo** [comment]
That would be awesome. One workaround I used recently is setting the autoDismiss property of false and than to true (because I was using 2 dialogs. One of them was shown only if a button from the first one is pressed and  I wanted the first dialog to stay when the user is finished with the 2 dialog). I have sped quite mush time on trying to get this working. Adding such an option would be very nice, indeed!

**Comment by afollestad** [comment]
@danielfaust I can add a `getProgressBar()` method, but why did you set the alpha? `View#setVisibility(int)` is designed to hide views.

`setVisibility(View.GONE)` will completely remove the view from visibility, including taking up space in the layout (other views will move to replace it until it's visible again).

**Comment by danielfaust** [comment]
@afollestad I tried using setVisibiliy. The problem that then comes up is that the dialog's dimensions change abruptly, as well as the location of the text within the dialog. It makes it feel buggy.

So I animated the alpha to hide the progress indicator to make it hide slowly, which does look good and indicates a transition into a new state, but the text then has a large empty area to its side, which looks wrong, unbalanced.

Ideally a fadeout of the progress indicator, together with an animated resize/relocate of the TextView would make it feel natural.

But as I didn't want to spend too much time on this issue, I opted cancel the progess dialog and immediately create a new one with the result. That feels good, uninterrupted. But having the ability to morph a progress dialog into a normal text-based one would feel more efficient.

**Comment by afollestad** [comment]
In my opinion, something like that is too much to include in this library. Dismissing the progress dialog and showing a regular dialog is the easiest solution, it's what would have to be done without this library.

However, I've been brainstorming ways to switch between different types of progress dialogs efficiently, so that might be possible later.

**Comment by AzureusSme** [comment]
Yes, thats the right way.
