### ISSUE TITLE
customView(custom_view, wrapInScrollView) doesn't work for me

### ISSUE THREAD

**Issue by Rainer-Lang** [afollestad/material-dialogs#654]
I use a custom view.
If I set the view with ```customView(cutom_view, false)``` all is shown.
If I set the view with ```customView(custom_view, true)``` not all is shown.

As custom view I use hsv-alpha-color-picker-android https://github.com/martin-stone/hsv-alpha-color-picker-android .

**Comment by afollestad** [comment]
This wouldn't really be an issue with this library as much as it would be an issue with how Android measures views. 

I'm assuming that happens because if you don't use a `ScrollView`, Android will try to fit all of the content in the dialog on screen. If you do use a ScrollView, it can use a comfortable max height and allow content to scroll. I've never had issues with this though.

**Comment by Rainer-Lang** [comment]
You say that I should put my custom view in a ScrollView and then pass to material-dialogs?
Is this right?

**Comment by afollestad** [comment]
I don't think that would be any different. That's already what the library does for you. 

You could probably make a custom `ScrollView` implementation or another parent layout implementation that measures itself differently. 

I can't do too much right now cause I just went through oral surgery for my wisdom teeth yet. So if you could look into it more that'd be helpful.

**Comment by Rainer-Lang** [comment]
Get well soon Aidan. Best wishes.
I will look and try some ideas.
Thanks for your reply.
