### ISSUE TITLE
Trigger material-dialog from outside an activity

### ISSUE THREAD

**Issue by femosso** [afollestad/material-dialogs#718]
Is it possible to trigger material-dialog from outside an activity or create an activity with material-dialog theme?

What I wanted is to open the material-dialog (or an activity that looks like one) when the user clicks on a notification. I can do this now by launching another activity which launches the dialog, but the activity gets behind the dialog, which I don't want to.

Thanks

**Comment by afollestad** [comment]
Android doesn't allow non-system apps to display dialogs outside of an Activity, nothing can be done about it.

What I've done is put a `DialogFragment` in an `Activity` (since dialog fragments survive orientation changes). The Activity uses a translucent theme so you can't see it. When the dialog closes, it finishes the Activity behind it.
