### ISSUE TITLE
Cancelable(false) not working

### ISSUE THREAD

**Issue by dzordz55** [afollestad/material-dialogs#938]
Hi,
In new viersion of library (0.8.5.4) cancelable() method not working. When i was set in my dialog builder cancelable(false), I was able to close dialog by touch outside the dialog. It works fine in previous version - 0.8.5.3.

**Comment by afollestad** [comment]
This library passes that value directly to the Android framework so it can't be a bug.

**Comment by afollestad** [comment]
If you're using it in a `DialogFragment`, you have to call `setCancelable(boolean)` on the DialogFragment instead

**Comment by mbarrben** [comment]
Well it's not working since https://github.com/afollestad/material-dialogs/pull/931. The reason is that in `Dialog` class `setCanceledOnTouchOutside` overrides cancelable property http://developer.android.com/intl/es/reference/android/app/Dialog.html#setCanceledOnTouchOutside(boolean) and it's being called after calling `setCancelable`.

**Comment by falkontre** [comment]
It should be reopened...It's not working too for me

**Comment by afollestad** [comment]
It's already been fixed in the code.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.5

**Comment by afollestad** [comment]
The above won't work until JitPack installs version 23.2.0 of the Google libs repo.

**Comment by mirzaadil** [comment]
dialog.setCanceledOnTouchOutside(false)
