### ISSUE TITLE
FolderChooserDialog.Builder does not work from within a PreferenceActivity

### ISSUE THREAD

**Issue by arcadian2** [afollestad/material-dialogs#948]
FolderChooserDialog.Builder requires an AppCompatActivity descendent. PreferenceActivity extends Activity, but not AppCompatActivity => I cannot use the file chooser in my preference fragments...

Can't you make the FileChooserDialog based on the more generic type "Activity"? I quickly looked at the code and it does not seem to actually require anything specific to AppCompatActivity.

Thanks,
Vincent.

**Comment by afollestad** [comment]
It does, it uses `getSupportFragmentManager()` since both the `FileChooserDialog` and `FolderChooserDialog` are Support Fragments.

---

I've made them accept `FragmentActivity` (which is the base of `AppCompatActivity`), but they cannot accept a regular `Activity`. I usually use an AppCompatActivity and manually embed `PreferenceFragments` in its layout (like the sample of this library does).

**Comment by dirkam** [comment]
Builder still does not accept FragmentActivity, only AppCompatActivity.
