### ISSUE TITLE
how to display dialog using context instead of activity(this) ?

### ISSUE THREAD

**Issue by SsKarthi** [afollestad/material-dialogs#957]
```java
 new MaterialDialog.Builder(context)    //instead of this(activity_name.this)
                .title("Warning")
                .content("Check Your Internet Connection")
                .positiveText("OK")
                .itemsGravity(GravityEnum.CENTER)
                .theme(Theme.LIGHT)
                .titleColorRes(android.R.color.black)
                .positiveColor(Color.rgb(31, 101, 160))
                .negativeColor(Color.rgb(31, 101, 160))
                .onPositive(new MaterialDialog.SingleButtonCallback() {
                    @Override
                    public void onClick(@NonNull MaterialDialog materialDialog, @NonNull DialogAction dialogAction) {
                    }
                })
                .show();
```

**Comment by Spoetnic** [comment]
When you use "ActivityName.this", you are using a Context.
The reason you need to write "ActivityName.this" and not just "this", is because you are starting the Dialog from a nested class. (for example an OnClickListener). When you would just write "this", it would pass the OnClickListener, where you actualy would pass the enclosing activity's "this".

That is why you need to add the ActivityName in front of this.
When you are in a Fragment, use "getActivity()".
When you are in an Activity, just use "this".

**Comment by afollestad** [comment]
@SsKarthi you really should use better code formatting and syntax highlighting for issues. Updated your OG comment.

@Spoetnic said what I would've said, though.

**Comment by afollestad** [comment]
You need an Activity though. A regular `Context` does not have a Window which dialogs can attach to.
