### ISSUE TITLE
Be able to specify the ColorChooser's horizontal and vertical item number.

### ISSUE THREAD

**Issue by csbenz** [afollestad/material-dialogs#980]
For example, if I want a GridView of colors of 4x4. As of now, the app would display it as 4 lines, with 5-5-5-1 items.

**Comment by afollestad** [comment]
Well, the layout is actually auto-fitting for available space: https://github.com/afollestad/material-dialogs/blob/master/commons/src/main/res/layout/md_stub_colorchooser_grid.xml

Changing this would make the color circles either very large or very small (since dialogs have a set maximum width, even on tablets).
